<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Asignar a_mdi mdi-chevron-down comboTr_77d82d</name>
   <tag></tag>
   <elementGuidId>241395c9-539c-4934-9f3b-8875fb206505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mdi.mdi-chevron-down.comboTreeArrowBtnImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comboTree517875ArrowBtn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-chevron-down comboTreeArrowBtnImg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comboTree517875ArrowBtn&quot;)/span[@class=&quot;mdi mdi-chevron-down comboTreeArrowBtnImg&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comboTree517875ArrowBtn']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
   </webElementXpaths>
</WebElementEntity>
